[build]
  base = "client"
  command = "npx vite build"
  publish = "dist"
  environment = { NETLIFY_NEXT_PLUGIN_SKIP = "true" }

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/transcribe-youtube"
  to = "/.netlify/functions/transcribe-youtube"
  status = 200

[[redirects]]
  from = "/api/transcribe-upload"
  to = "/.netlify/functions/transcribe-upload"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200